/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface SignalPosition {
  'latitude' : number,
  'compassHeading' : number,
  'longitude' : number,
  'timestamp' : bigint,
  'tiltAngle' : number,
  'heightRecommendation' : bigint,
  'rssiDbm' : bigint,
}
export interface Tower {
  'region' : string,
  'latitude' : number,
  'name' : string,
  'longitude' : number,
}
export interface _SERVICE {
  'addTower' : ActorMethod<[string, string, number, number], undefined>,
  'clearSignalPositions' : ActorMethod<[], undefined>,
  'getAllAppSettings' : ActorMethod<[], Array<[string, string]>>,
  'getAppSetting' : ActorMethod<[string], [] | [string]>,
  'getSignalPositions' : ActorMethod<[], Array<SignalPosition>>,
  'getTowerByName' : ActorMethod<[string], [] | [Tower]>,
  'getTowers' : ActorMethod<[], Array<Tower>>,
  'saveSignalPosition' : ActorMethod<
    [string, number, number, number, bigint, bigint, number],
    undefined
  >,
  'setAppSetting' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];