/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunitySignalReport {
  'id' : bigint,
  'latitude' : number,
  'quality' : SignalQuality,
  'note' : [] | [string],
  'longitude' : number,
  'timestamp' : bigint,
}
export interface CoverageGapReport {
  'id' : bigint,
  'latitude' : number,
  'description' : string,
  'longitude' : number,
  'timestamp' : bigint,
}
export interface SignalPosition {
  'latitude' : number,
  'compassHeading' : number,
  'longitude' : number,
  'timestamp' : bigint,
  'tiltAngle' : number,
  'heightRecommendation' : bigint,
  'rssiDbm' : bigint,
}
export type SignalQuality = { 'Good' : null } |
  { 'None' : null } |
  { 'Weak' : null } |
  { 'Excellent' : null };
export interface Tower {
  'region' : string,
  'latitude' : number,
  'name' : string,
  'longitude' : number,
}
export interface TowerStatusLog {
  'latencyMs' : bigint,
  'timestamp' : bigint,
  'towerName' : string,
  'reachable' : boolean,
}
export interface _SERVICE {
  'addCommunitySignalReport' : ActorMethod<
    [number, number, SignalQuality, [] | [string]],
    bigint
  >,
  'addCoverageGapReport' : ActorMethod<[number, number, string], bigint>,
  'addTower' : ActorMethod<[string, string, number, number], undefined>,
  'addTowerStatusLog' : ActorMethod<[string, boolean, bigint], bigint>,
  'clearCommunitySignalReports' : ActorMethod<[], undefined>,
  'clearOldTowerStatusLogs' : ActorMethod<[bigint], undefined>,
  'clearSignalPositions' : ActorMethod<[], undefined>,
  'getAllAppSettings' : ActorMethod<[], Array<[string, string]>>,
  'getAllTowerStatusLogs' : ActorMethod<[], Array<TowerStatusLog>>,
  'getAppSetting' : ActorMethod<[string], [] | [string]>,
  'getCommunitySignalReports' : ActorMethod<[], Array<CommunitySignalReport>>,
  'getCoverageGapReports' : ActorMethod<[], Array<CoverageGapReport>>,
  'getSignalPositions' : ActorMethod<[], Array<SignalPosition>>,
  'getTowerByName' : ActorMethod<[string], [] | [Tower]>,
  'getTowers' : ActorMethod<[], Array<Tower>>,
  'saveSignalPosition' : ActorMethod<
    [string, number, number, number, bigint, bigint, number],
    undefined
  >,
  'setAppSetting' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];