/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SignalQuality = IDL.Variant({
  'Good' : IDL.Null,
  'None' : IDL.Null,
  'Weak' : IDL.Null,
  'Excellent' : IDL.Null,
});
export const TowerStatusLog = IDL.Record({
  'latencyMs' : IDL.Nat,
  'timestamp' : IDL.Int,
  'towerName' : IDL.Text,
  'reachable' : IDL.Bool,
});
export const CommunitySignalReport = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'quality' : SignalQuality,
  'note' : IDL.Opt(IDL.Text),
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const CoverageGapReport = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const SignalPosition = IDL.Record({
  'latitude' : IDL.Float64,
  'compassHeading' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
  'tiltAngle' : IDL.Float64,
  'heightRecommendation' : IDL.Nat,
  'rssiDbm' : IDL.Nat,
});
export const Tower = IDL.Record({
  'region' : IDL.Text,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addCommunitySignalReport' : IDL.Func(
      [IDL.Float64, IDL.Float64, SignalQuality, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addCoverageGapReport' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTower' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Float64], [], []),
  'addTowerStatusLog' : IDL.Func([IDL.Text, IDL.Bool, IDL.Nat], [IDL.Nat], []),
  'clearCommunitySignalReports' : IDL.Func([], [], []),
  'clearOldTowerStatusLogs' : IDL.Func([IDL.Nat], [], []),
  'clearSignalPositions' : IDL.Func([], [], []),
  'getAllAppSettings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllTowerStatusLogs' : IDL.Func([], [IDL.Vec(TowerStatusLog)], ['query']),
  'getAppSetting' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getCommunitySignalReports' : IDL.Func(
      [],
      [IDL.Vec(CommunitySignalReport)],
      ['query'],
    ),
  'getCoverageGapReports' : IDL.Func(
      [],
      [IDL.Vec(CoverageGapReport)],
      ['query'],
    ),
  'getSignalPositions' : IDL.Func([], [IDL.Vec(SignalPosition)], ['query']),
  'getTowerByName' : IDL.Func([IDL.Text], [IDL.Opt(Tower)], ['query']),
  'getTowers' : IDL.Func([], [IDL.Vec(Tower)], ['query']),
  'saveSignalPosition' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'setAppSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SignalQuality = IDL.Variant({
    'Good' : IDL.Null,
    'None' : IDL.Null,
    'Weak' : IDL.Null,
    'Excellent' : IDL.Null,
  });
  const TowerStatusLog = IDL.Record({
    'latencyMs' : IDL.Nat,
    'timestamp' : IDL.Int,
    'towerName' : IDL.Text,
    'reachable' : IDL.Bool,
  });
  const CommunitySignalReport = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'quality' : SignalQuality,
    'note' : IDL.Opt(IDL.Text),
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const CoverageGapReport = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const SignalPosition = IDL.Record({
    'latitude' : IDL.Float64,
    'compassHeading' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
    'tiltAngle' : IDL.Float64,
    'heightRecommendation' : IDL.Nat,
    'rssiDbm' : IDL.Nat,
  });
  const Tower = IDL.Record({
    'region' : IDL.Text,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  
  return IDL.Service({
    'addCommunitySignalReport' : IDL.Func(
        [IDL.Float64, IDL.Float64, SignalQuality, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addCoverageGapReport' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTower' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'addTowerStatusLog' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'clearCommunitySignalReports' : IDL.Func([], [], []),
    'clearOldTowerStatusLogs' : IDL.Func([IDL.Nat], [], []),
    'clearSignalPositions' : IDL.Func([], [], []),
    'getAllAppSettings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllTowerStatusLogs' : IDL.Func(
        [],
        [IDL.Vec(TowerStatusLog)],
        ['query'],
      ),
    'getAppSetting' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getCommunitySignalReports' : IDL.Func(
        [],
        [IDL.Vec(CommunitySignalReport)],
        ['query'],
      ),
    'getCoverageGapReports' : IDL.Func(
        [],
        [IDL.Vec(CoverageGapReport)],
        ['query'],
      ),
    'getSignalPositions' : IDL.Func([], [IDL.Vec(SignalPosition)], ['query']),
    'getTowerByName' : IDL.Func([IDL.Text], [IDL.Opt(Tower)], ['query']),
    'getTowers' : IDL.Func([], [IDL.Vec(Tower)], ['query']),
    'saveSignalPosition' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'setAppSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };